default: &default
  ci_builds_batch_archive_trace_cron_job:
    class: "Ci::Builds::BatchArchiveTraceJob"
    schedule: "1 * * * *"
  remove_expired_members_job:
    class: "RemoveExpiredMembersJob"
    schedule: "10 0 * * *"
  drop_running_job:
    class: "Ci::StuckBuilds::DropRunningJob"
    schedule: "*/30 * * * *"
  drop_pending_job:
    class: "Ci::StuckBuilds::DropPendingJob"
    schedule: "0 * * * *"
  drop_scheduled_job:
    class: "Ci::StuckBuilds::DropScheduledJob"
    schedule: "35 * * * *"


development:
  <<: *default

production:
  <<: *default

# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
